language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install libboost-program-options-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libspdlog-dev -y
- sudo apt-get install doxygen -y
- sudo apt-get install doxygen-doc -y
- sudo apt-get install doxygen-latex -y
- sudo apt-get install doxygen-gui -y
- sudo apt-get install graphviz -y
script:
- mkdir bin
- cd bin
- cmake ../src
- make all
- make test
- make package
deploy:
  provider: script
  skip_cleanup: true
  script: 
  - doxygen
  - cp -r html/* ../docs/
  - git add -f ../docs
  - git commit -m 'update docs 0.0.$TRAVIS_BUILD_NUMBER'
  - git push "https://madmazoku:$GITHUB_API_KEY@github.com/madmazoku/otus.lessons.08.01"
  - curl -T otus.lessons.08.01-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umadmazoku:$BINTRAY_API_KEY "https://api.bintray.com/content/madmazoku/otus.lessons/08.01/$TRAVIS_BUILD_NUMBER/otus.lessons.08.01-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
